[functions]
  # Diretório raiz das funções (se for diferente da raiz do projeto)
  directory = "src"
  # Caminho para o servidor do Node
  external_node_modules = true
  [functions.command]
  # Comando para iniciar o servidor
  command = "npm start"